### ISSUE TITLE
wupiao not working with ssl

### ISSUE THREAD

**Issue by upolymorph** [cornelius-keller/ansible-coreos-kubernetes#11]
I finally found the issue I was looking for since a long time and preventing the kubernetes worker components to start: wupiao is not working with ssl certificates. I cannot understand how this playbook could have been working with wupiao and could not see how I can be the only one to have this issue.
Just try wupiao 127.0.0.1 on a worker node and you should see it.

**Comment by cornelius-keller** [comment]
@upolymorph  I thinks this is fixed in my master. I repalced wupio by a curl request using the ssl certificates.

**Comment by upolymorph** [comment]
@cornelius-keller you fixed it 6 days ago ... :-( this means that the code a pull 1 month ago wasn't working .... it should have saved a lot of time if I knew it.
