### ISSUE TITLE
Iptables problems?

### ISSUE THREAD

**Issue by khusseini** [cornelius-keller/ansible-coreos-kubernetes#14]
Hey,

I have worked with this setup and modified it slightly (used rook for ceph).
Things are working well, however something is preventing incoming http and https connections to the coreos box. Are there any firewalls or iptables that one should be aware of?

**Comment by cornelius-keller** [comment]
Hi @khusseini there is a calico firewall protecting the hosts.
However if you use the latest version http and https should be white listed.

**Comment by khusseini** [comment]
Would it be the whitelist in this policy?
https://github.com/cornelius-keller/ansible-coreos-kubernetes/blob/master/roles/calico/templates/cluster_policy.yml

**Comment by cornelius-keller** [comment]
that is the cluster internal policy for whitlisting stuff that should be visible only internal to the cluster.
I just revied the code and saw that the actual whitelisting I did was not in the public repository. I just pushed added it into the failsave policy https://github.com/cornelius-keller/ansible-coreos-kubernetes/blob/master/roles/calico/templates/failsafe_policy.yml  with https://github.com/cornelius-keller/ansible-coreos-kubernetes/commit/e20ccf5b9be99f8eef7fff5c681e3194d5ae0955

**Comment by cornelius-keller** [comment]
it is also possible to create a custom policy file. then source the calico.env file in <inventory_dir>/<clustername>-calico/ and do a calicoctl apply -f <your policy file >

**Comment by khusseini** [comment]
Amazing! Thanks!!!
