### ISSUE TITLE
Format of authorized key for hetzner

### ISSUE THREAD

**Issue by upolymorph** [cornelius-keller/ansible-coreos-kubernetes#2]
What is the format expected for authorized key in inventory ini for the rescue mode? this is not documented. currently I get always a error 400 when running bootstrap.

Error from task boot-rescue: activate rescue mode on server from hetzner

fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "connection": "close", "content": "{\"error\":{\"status\":400,\"code\":\"INVALID_INPUT\",\"message\":\"invalid input\",\"missing\":null,\"invalid\":[\"authorized_key\"]}}", "content_length": "117", "content_type": "application/json; charset=utf-8", "date": "Wed, 07 Dec 2016 10:57:36 GMT", "failed": true, "json": {"error": {"code": "INVALID_INPUT", "invalid": ["authorized_key"], "message": "invalid input", "missing": null, "status": 400}}, "msg": "Status code was not [200]", "redirected": false, "server": "Apache", "status": 400}

**Comment by cornelius-keller** [comment]
Hi @upolymorph , if you log into hetzner and go to ther server list you see a Button "key management" above it.
There you have to upload the public key you want to use.
Then it shows you the fingerprint of the key you updloaded. This fingerprint you have tho use as the  the rescue_authorized_key.

Hope that gets you runnig.
Sorry for answering so late, it was a busy week. Next time I'll be faster.

**Comment by upolymorph** [comment]
Stills have issue to activate rescue mode.
I used the fingerprint in inventory.ini 
rescue_authorized_key=12:d0:XX:XX:XX:XX:XX:XX:XX:e2:fb:XX:XX:XX:12:7c

but still get message:

TASK [boot-rescue : activate rescue mode] **************************************
Monday 26 December 2016  09:48:14 +0100 (0:00:00.487)       0:00:00.573 ******* 
fatal: [88.99.56.238]: FAILED! => {"changed": false, "connection": "close", "content": "{\"error\":{\"status\":400,\"code\":\"INVALID_INPUT\",\"message\":\"invalid input\",\"missing\":null,\"invalid\":[\"authorized_key\"]}}", "content_length": "117", "content_type": "application/json; charset=utf-8", "date": "Mon, 26 Dec 2016 08:48:14 GMT", "failed": true, "json": {"error": {"code": "INVALID_INPUT", "invalid": ["authorized_key"], "message": "invalid input", "missing": null, "status": 400}}, "msg": "Status code was not [200]", "redirected": false, "server": "Apache", "status": 400}
fatal: [88.99.56.196]: FAILED! => {"changed": false, "connection": "close", "content": "{\"error\":{\"status\":400,\"code\":\"INVALID_INPUT\",\"message\":\"invalid input\",\"missing\":null,\"invalid\":[\"authorized_key\"]}}", "content_length": "117", "content_type": "application/json; charset=utf-8", "date": "Mon, 26 Dec 2016 08:48:14 GMT", "failed": true, "json": {"error": {"code": "INVALID_INPUT", "invalid": ["authorized_key"], "message": "invalid input", "missing": null, "status": 400}}, "msg": "Status code was not [200]", "redirected": false, "server": "Apache", "status": 400}
fatal: [88.99.56.213]: FAILED! => {"changed": false, "connection": "close", "content": "{\"error\":{\"status\":400,\"code\":\"INVALID_INPUT\",\"message\":\"invalid input\",\"missing\":null,\"invalid\":[\"authorized_key\"]}}", "content_length": "117", "content_type": "application/json; charset=utf-8", "date": "Mon, 26 Dec 2016 08:48:14 GMT", "failed": true, "json": {"error": {"code": "INVALID_INPUT", "invalid": ["authorized_key"], "message": "invalid input", "missing": null, "status": 400}}, "msg": "Status code was not [200]", "redirected": false, "server": "Apache", "status": 400}

in any case I do not see how this could help ansible to select the correct private ssh key to enable rescue mode ...

**Comment by cornelius-keller** [comment]
Hi @upolymorph,

did you upload your public key inside the hetzner web interface?

**Comment by cornelius-keller** [comment]
Hi @upolymorph, it seems to me that you are not having a problem with the authorized key.
It seems to me that your webservice username and password is incorrect.

**Comment by cornelius-keller** [comment]
@upolymorph : hi again. I started to do a getting started documentation for hetzer. I hope this helps to clarify thinkgs. You'll find it here: [getting started](https://github.com/cornelius-keller/ansible-coroeos-kubernetes/blob/master/docs/getting_started_hetzner.md)
