### ISSUE TITLE
ceph_osd_type

### ISSUE THREAD

**Issue by upolymorph** [cornelius-keller/ansible-coreos-kubernetes#3]
in task [ceph-on-kubernetes-config : templtae k8s resources] there is an error that ceph_osd_type is not defined. This should be defined in the inventory.ini however the sample provider do not have shuch an entry. to update the sample file and to document configuration can you provide the ceph_osd_type that are supported and what are the depending config vars required depending on the type.

**Comment by cornelius-keller** [comment]
Hi @upolymorph I think I did this in https://github.com/cornelius-keller/ansible-coreos-kubernetes/commit/7d1e96899389774de7aab9dce2edf0b8314cf3c1 for the hetzner sample inventory. 
Values for this variable can be osd_directory if you dont have a whole disk to use, or osd_disk if you can use a whole other disk.
Can you pull / rebase to my master and verify?
Was the getting started documentation I provided helpful?
In general I think I should dedicate a whole separate documentation page to the ceph setup, I hope I'll find the time in the next days.

**Comment by upolymorph** [comment]
Hi @cornelius-keller I am writing a documentation from scratch as it is easier for me while I do not have any knowledge about the solution not default config on my computer. I should make a pull request by tomorrow with bug fixes and documentation. We can then see from there if update are required or what enhancement should be performed.

**Comment by upolymorph** [comment]
deployment, check and usage of ceph on this cluster should be documented.
